class Label:
    ANXIOUS = 'anxious'
    ATAXIC = 'ataxic'
    HEALTHY = 'healthy'
    HYPOKENITC_FRONTAL = 'hypokinetic-frontal'
    PARETIC = 'paretic'
    SENSORY_ATAXIC = 'sensory-ataxic'
    ANTALGIC = 'antalgic'
    DYSKINETIC = 'dyskinetic'
    FUNCTIONAL = 'functional'
    HYPOKENITC = 'hypokinetic'
    MOTOR_COGNITIVE = 'motor-cognitive'
    SPASTIC = 'spastic'
